from pydantic import BaseModel, Field
from typing import List, Optional


# ── Reused by existing similarity & summarize endpoints ──────────────────────

class SummaryResponse(BaseModel):
    summary: str


class SimilarityResponse(BaseModel):
    similarity: float


# ── Novelty Analysis — nested building blocks ────────────────────────────────

class TopMatch(BaseModel):
    """A single paper ranked by semantic similarity to the user abstract."""
    paperId: str
    title: str
    similarity: float = Field(..., description="Cosine similarity score between 0 and 1")
    year: Optional[int] = Field(default=None, description="Publication year of the matched paper")
    citationCount: Optional[int] = Field(default=None, description="Citation count of the matched paper")


class SemanticSimilarityMetrics(BaseModel):
    """Raw similarity statistics computed across all retrieved papers."""
    highest: float = Field(..., description="Highest cosine similarity found among all papers")
    average: float = Field(..., description="Mean cosine similarity across all papers")
    lowest: float = Field(..., description="Lowest cosine similarity found among all papers")


class KeywordNovelty(BaseModel):
    """Keyword-level novelty analysis comparing user keywords against paper corpus."""
    userKeywords: List[str] = Field(..., description="Important keywords extracted from the user abstract")
    novelKeywords: List[str] = Field(..., description="Keywords not found in any retrieved paper")
    overlapKeywords: List[str] = Field(..., description="Keywords that overlap with existing literature")
    keywordNoveltyScore: float = Field(..., description="Ratio of novel keywords to total keywords (0 to 1)")


class ResearchMaturity(BaseModel):
    """
    Maturity signal derived from publication years and citation counts.
    Helps estimate whether the research area is emerging or saturated.
    """
    averageYear: Optional[float] = Field(default=None, description="Average publication year of retrieved papers")
    averageCitationCount: Optional[float] = Field(default=None, description="Average citation count of retrieved papers")
    maturityLabel: str = Field(..., description="One of: Emerging, Developing, Established, Saturated")
    maturityScore: float = Field(..., description="Normalized maturity score between 0 (emerging) and 1 (saturated)")


class InnovationReport(BaseModel):
    """
    Human-readable explainable report generated by the report service.
    Structured as strengths, weaknesses, and actionable recommendations.
    """
    strengths: List[str] = Field(..., description="Aspects where the user's abstract shows originality")
    weaknesses: List[str] = Field(..., description="Aspects where the abstract overlaps with existing work")
    recommendations: List[str] = Field(..., description="Actionable suggestions to improve research novelty")
    summary: str = Field(..., description="One-paragraph narrative summary of the novelty analysis")


# ── Main response returned to Spring Boot ────────────────────────────────────

class NoveltyAnalysisResponse(BaseModel):
    """
    The complete novelty analysis result returned by the /ai/novelty-check endpoint.
    Consumed by the Spring Boot backend and surfaced to the React frontend.
    """
    innovationScore: float = Field(..., description="Final innovation score between 0 and 100")
    semanticSimilarity: SemanticSimilarityMetrics
    topMatches: List[TopMatch] = Field(..., description="Top 5 most similar papers ranked by similarity")
    keywordNovelty: KeywordNovelty
    researchMaturity: ResearchMaturity
    report: InnovationReport
