spring.application.name=researchhub

spring.datasource.url=jdbc:postgresql://localhost:5432/researchhub
spring.datasource.username=postgres
spring.datasource.password=alex

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080